import type { Metadata } from "next";

import "antd/dist/reset.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "官网 | 星辰咖啡 Satorivia Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
